# Generated by Django 4.2.4 on 2023-08-28 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Номер вывода')),
                ('name', models.CharField(max_length=50, verbose_name='Имя колоды')),
                ('packtype', models.CharField(choices=[('TXT', 'Text pack'), ('IMG', 'Image pack')], default='TXT', max_length=3, verbose_name='Тип колоды')),
            ],
        ),
        migrations.CreateModel(
            name='Steplist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stepname', models.CharField(max_length=50, verbose_name='Имя шага')),
                ('funcname', models.CharField(max_length=50, verbose_name='Функция теущего шага')),
            ],
        ),
        migrations.CreateModel(
            name='Chatusers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatid', models.TextField(verbose_name='Идентификатор чата')),
                ('name', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('isvalid', models.BooleanField(verbose_name='Запись подтверждена')),
                ('isactive', models.BooleanField(verbose_name='Запись активна')),
                ('curstep', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='botbackend.steplist', verbose_name='Текущий шаг')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=3, verbose_name='Отображаемое число')),
                ('cardtext', models.TextField(verbose_name='Текст или ссылка на файл')),
                ('pack', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='botbackend.pack', verbose_name='Колода')),
            ],
        ),
    ]
