# Generated by Django 4.2.4 on 2023-08-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botbackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pack',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='pack',
            name='packtype',
            field=models.CharField(choices=[('TXT', 'Текстовая колода'), ('IMG', 'Колода с рисунками')], default='TXT', max_length=3, verbose_name='Тип колоды'),
        ),
        migrations.AddIndex(
            model_name='pack',
            index=models.Index(fields=['name'], name='botbackend__name_f1279b_idx'),
        ),
    ]
