# Generated by Django 4.2.4 on 2023-08-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botbackend', '0002_alter_pack_options_alter_pack_packtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='packtype',
            field=models.CharField(choices=[('TXT', 'Текстовая колода'), ('IMG', 'Колода с рисунками')], default='TXT', max_length=3, unique=True, verbose_name='Тип колоды'),
        ),
    ]
