# Generated by Django 4.2.4 on 2023-08-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botbackend', '0003_alter_pack_packtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Имя колоды'),
        ),
        migrations.AlterField(
            model_name='pack',
            name='packtype',
            field=models.CharField(choices=[('TXT', 'Текстовая колода'), ('IMG', 'Колода с рисунками')], default='TXT', max_length=3, verbose_name='Тип колоды'),
        ),
    ]
