# Generated by Django 4.2.4 on 2023-08-28 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botbackend', '0004_alter_pack_name_alter_pack_packtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botbackend.pack', verbose_name='Колода'),
        ),
    ]
