# Generated by Django 4.2.4 on 2023-08-29 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botbackend', '0008_alter_chatusers_curstep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatusers',
            name='isvalid',
        ),
        migrations.AlterField(
            model_name='chatusers',
            name='curstep',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='botbackend.pack', verbose_name='Текущая колода'),
        ),
        migrations.AlterField(
            model_name='chatusers',
            name='isactive',
            field=models.BooleanField(default=False, verbose_name='Запись активна'),
        ),
    ]
