# Generated by Django 4.2.4 on 2023-08-29 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botbackend', '0009_remove_chatusers_isvalid_alter_chatusers_curstep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatusers',
            name='curstep',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='botbackend.pack', verbose_name='Текущая колода'),
        ),
    ]
