# Generated by Django 4.2.4 on 2023-09-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botbackend', '0011_alter_chatusers_curstep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatusers',
            name='name',
            field=models.CharField(max_length=110, verbose_name='Имя пользователя'),
        ),
    ]
