# Generated by Django 4.2.4 on 2023-09-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botbackend', '0012_alter_chatusers_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatusers',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=110, null=True, verbose_name='Имя пользователя'),
        ),
    ]
