# Generated by Django 4.2.4 on 2023-09-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botbackend', '0013_alter_chatusers_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='packtype',
            field=models.CharField(choices=[('TXT', 'Текстовая колода'), ('IMG', 'Колода с рисунками'), ('CTJ', 'Текстовая колода, формирующая рисунок')], default='TXT', max_length=3, verbose_name='Тип колоды'),
        ),
    ]
